### PR TITLE
Idealised moist docs

### PR DESCRIPTION
**Pull request by RuthG**
Here are the corrections to my previous pull request. 
Apologies for the new branch, I decided to rename my local branch and this seems to have caused some problems with the remotes.

### CODE REVIEW

**Review by mp586 — APPROVED** [review]

**Comment by mp586** [comment]
are we supposed to add an Authors section or is that optional?

**Review by rosscastle — APPROVED** [review]
Really really nice! 

I think the only issue I can find is that the file itself (and therefore in the index) has idealized spelt with an s (correctly) not a z (as per the model code), but I think we can ignore this!

**Comment by RuthG** [comment]
Thanks for checking it, I've added the authors at the bottom, I forgot about that. Happy to merge?

**Comment by rosscastle** [comment]
> Thanks for checking it, I've added the authors at the bottom, I forgot about that. Happy to merge?

Merge time!

**Comment by mp586** [comment]
yes! :)

**Pull request merged**
