### PR TITLE
Porting isca

### PR DESCRIPTION
**Pull request by wanyingkang**
Hi! I clean up the code a little bit to include only the changes regarding porting. See if it is ok. --W

### CODE REVIEW

**Comment by jamesp** [comment]
Hi Wanying,

How does this PR differ from the one you submitted previously?  Is it possible to put your latest changes into the previous PR #55?  I think we are about ready to merge that one.

**Comment by wanyingkang** [comment]
Hi James,

In the new Pull Request, I tried to get rid of my personal setups, so that it could be merged to the main branch easier. Also, the Ncar machine changed many directories’ name, the adjustment is necessary to make the simulation possible. 
After you merge it, I can help test it in the Ncar machine to make sure it works.

—W

**Comment by jamesp** [comment]
Ah I see.  Can you merge these changes into your `ncar_isca` branch?  Then it will all go in together.

**Comment by wanyingkang** [comment]
Hi James, 

Everything necessary is in the head of branch “porting_isca”, which I sent a PR for. I can submit another PR if it becomes confusing now… 

Cheers,
—W

**Comment by jamesp** [comment]
Please don't make any more pull requests, the ones we have should be sufficient.  looking at your branches, I think that `ncar_isca` and `porting_isca` are at the same state, so both these PRs have the same state.  I will close this one and merge #55.

**Pull request closed without merging**
