### PR TITLE
Small fixes for test cases that fail under gfortran

### PR DESCRIPTION
**Pull request by sit23**
As described in #221, some of the test cases are failing when run under gfortran. I've identified and fixed two of these 3 issues, and am working on the 3rd. The changes are as follows:

* The axisymmetric case was failing because we were supplying dt_rad as a float when it should have been an integer. Intel didn’t mind this, but gfortran objects.
* The Top down test seg-faulted because one of the loops over the y dimension was looping over the length of the x dimension instead
* I’ve had a look at the giant-planet test case to see if I can see anything obvious. I’ve made a few changes that might help, but I’d need to get a working example of what the problem is before I can make too much progress. 

I'm running the trip tests on these now to see what progress I might have made, but as they all failed previously, this is more just to check that they now run.

### CODE REVIEW

**Comment by RuthG** [comment]
Looks good to me!

**Comment by sit23** [comment]
Thanks @RuthG - would you mind doing a review and approving it so that I can merge it in? Thanks!

**Review by RuthG — APPROVED** [review]
Changes are minor bug fixes, confirmed not to influence trip tests on intel compilers. I am happy for these to be merged in, thanks for spotting it all Stephen! :)

**Comment by sit23** [comment]
Thanks @RuthG

**Pull request merged**
