### PR TITLE
Add 2m specific humidity and relative humidity

### PR DESCRIPTION
**Pull request by lqxyz**
Add 2m specific humidity and relative humidity.
Output example:
`diag.add_field('atmosphere', 'sphum_2m', time_avg=True)  # add 2m specific humidity`
`diag.add_field('atmosphere', 'rh_2m', time_avg=True)  # add 2m relative humidity`

### CODE REVIEW

**Comment by penmaher** [comment]
Thanks @lqxyz. Could you do me a favour and add two extra diagnostics to your PR? This will make it easier than adding another stage to the current PR.

1. 
https://github.com/ExeClim/Isca/blob/c38d2ff0ba0ee2240bf919df966ab36eb1885eb7/src/atmos_spectral/driver/solo/idealized_moist_phys.F90#L263

add the IDs

     _id_cin,           &
     id_flux_u,      &
     id_flux_v_

then https://github.com/ExeClim/Isca/blob/c38d2ff0ba0ee2240bf919df966ab36eb1885eb7/src/atmos_spectral/driver/solo/idealized_moist_phys.F90#L609

add 

_id_flux_u = register_diag_field(mod_name, 'flux_u',          &
     axes(1:2), Time, 'Zonal momentum flux','Pa')
id_flux_v = register_diag_field(mod_name, 'flux_v',          &
     axes(1:2), Time, 'Meridional momentum flux','Pa')_

and then after the call to surface_flux https://github.com/ExeClim/Isca/blob/c38d2ff0ba0ee2240bf919df966ab36eb1885eb7/src/atmos_spectral/driver/solo/idealized_moist_phys.F90#L986

add

   _if(id_flux_u  > 0) used = send_data(id_flux_u, flux_u, Time)
   if(id_flux_v  > 0) used = send_data(id_flux_v, flux_v, Time)_
 
These should then be part of the testing @sit23 suggested. Sorry for the extra work. I thought this might be easier in the long run. 

Once you make these changes to your code, push them and they will automatically become part of the PR.

**Comment by lqxyz** [comment]
Hi @penmaher, I have added the two extra diagnostics as you suggested. Thank you very much for the help.

**Comment by lqxyz** [comment]
Hi @sit23, when running the `trip_test`, I found that one experiment `axisymmetric` has failed and here are the results:
```
Results for all of the test cases ran comparing c38d2ff and b9888bc are as follows...
socrates_aquaplanet : pass
variable_co2_grey : pass
realistic_continents_fixed_sst : pass
realistic_continents_variable_qflux : pass
held_suarez : pass
variable_co2_rrtm : pass
bucket_model : pass
top_down_test : pass
frierson : pass
axisymmetric : fail
MiMA : pass
giant_planet : pass
Nightmare, some tests have failed
```
This failure also exists in the commit `447a37a` of this P/R:
```
Results for all of the test cases ran comparing c38d2ff and 447a37a are as follows...
axisymmetric : fail
Nightmare, some tests have failed
```

Looking at the error messages, e.g. ` isca - DEBUG - FATAL from PE  2: lookup_es_1d: saturation vapor pressure table overflow, nbad=128`,  it seems that the problem is possibly from the calculation of saturation water vapour pressure by `escomp(temp_2m, e_sat_2m)` (see  https://github.com/ExeClim/Isca/pull/92/files#diff-b599cb8a704e13b215d5560186006611R545), where the `temp_2m` may have some unreasonable values.

When checking the values of `temp_2m`,  I found some of them are `NaN`,  which are from the `NaN` values in `ex_del_h` (see https://github.com/ExeClim/Isca/pull/92/files#diff-b599cb8a704e13b215d5560186006611R518 and https://github.com/ExeClim/Isca/pull/92/files#diff-b599cb8a704e13b215d5560186006611R526), indicating that there are some potential problems in the `mo_profile` subroutine. I will confim this later.

**Comment by lqxyz** [comment]
The possible reasons I guess are some arrays such as `zeta_t` within the `where` statement from line `609`  to line `617` in `src/atmos_param/monin_obukhov/monin_obukhov_kernel.F90` are not initialised, so some of them may not have reasonable values before being passed to the subroutine `monin_obukhov_integral_tq`, leading to the returned arrays such as `f_t_ref` or `f_t` contain some unreasonable values. Therefore, `del_t = 1.0 - f_t_ref/f_t` in line `631` of `monin_obukhov_kernel.F90` will produce some unreasonable values in the end, which is the `ex_del_h` in the `mo_profile` subroutine.

https://github.com/ExeClim/Isca/blob/master/src/atmos_param/monin_obukhov/monin_obukhov_kernel.F90#L609-L617

**Comment by lqxyz** [comment]
Hi @sit23, after the arrays such as `zeta_t` and `zeta_q` being initialised to zeros in [`monin_obukhov_kernel.F90`](https://github.com/ExeClim/Isca/blob/master/src/atmos_param/monin_obukhov/monin_obukhov_kernel.F90#L609-L617), I found that it can finally pass all the tests in `trip_test` and here are the results ([`c38d2ff`](https://github.com/ExeClim/Isca/commit/c38d2ff0ba0ee2240bf919df966ab36eb1885eb7) is the current master commit and [`325400e`](https://github.com/ExeClim/Isca/pull/92/commits/325400e5b7446fd968c46707cb4bb79fda24ca3c) is the new commit in this P/R):

```
Results for all of the test cases ran comparing c38d2ff and 325400e are as follows...
socrates_aquaplanet : pass
variable_co2_grey : pass
realistic_continents_fixed_sst : pass
realistic_continents_variable_qflux : pass
held_suarez : pass
variable_co2_rrtm : pass
bucket_model : pass
top_down_test : pass
frierson : pass
axisymmetric : pass
MiMA : pass
giant_planet : pass
Congratulations, all tests have passed
```

**Comment by lqxyz** [comment]
Thank you @sit23, I've made the requested changes.

**Comment by sit23** [comment]
Thanks @lqxyz - I'll merge this in now. Nice work.

**Pull request merged**
