### PR TITLE
Two stream gray docs

### PR DESCRIPTION
**Pull request by ntlewis**
This PR addresses issue #132 by adding documentation for two_stream_gray_rad.

### CODE REVIEW

**Comment by RuthG** [comment]
Hi Neil, 

I've just taken a quick look over this, the structure and description of what each scheme does look good to me! Just a few typos to flag up:
l35: available
l37: available
l202: diurnal
l402: calculations

**Comment by ntlewis** [comment]
Hi Ruth,

Thanks for taking a look, are you happy to approve this once these changes have been made or would you rather look over it in more detail at some point?

While I correct the typos I’ll also have another look through to see if there are any that have evaded both of us!

Neil



On 20 Jul 2020, at 14:16, RuthG <notifications@github.com> wrote:

﻿

Hi Neil,

I've just taken a quick look over this, the structure and description of what each scheme does look good to me! Just a few typos to flag up:
l35: available
l37: available
l202: diurnal
l402: calculations

**Comment by RuthG** [comment]
Hi Neil,

Something I just thought of - I’ll do a quick check whether the default parameters in the Geen scheme are the version I think should be stable with the slab ocean, and we can add a recommendation (or perhaps change the defaults in the master) if not. I’ll also remind myself what variations around BoG we’ve tried over the years and check that against the model defaults and BoG paper.
I will find a moment to do all that by the weekend, and let you know what I find and if I think any comment should be added about those namelist choices.

Aside from that I’d be happy to approve it, I think it covers all the key points, I don’t see any code/science problems and it explains what is going on clearly. Matthew’s down as quality control, so that will give a second pair of eyes on it.

Thanks for writing it!

Ruth


On 20 Jul 2020, at 18:38, Neil Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


Hi Ruth,

Thanks for taking a look, are you happy to approve this once these changes have been made or would you rather look over it in more detail at some point?

While I correct the typos I’ll also have another look through to see if there are any that have evaded both of us!

Neil



On 20 Jul 2020, at 14:16, RuthG <notifications@github.com<mailto:notifications@github.com>> wrote:

﻿

Hi Neil,

I've just taken a quick look over this, the structure and description of what each scheme does look good to me! Just a few typos to flag up:
l35: available
l37: available
l202: diurnal
l402: calculations

**Comment by matthewjhenry** [comment]
Great job @ntlewis and @RuthG. This is very thorough and helpful documentation! :) 

Happy to push when these comments are considered (some are mere suggestions).

Comments:
- typos 'available'
- L. 67: 'relative to the :math:`^{k}` term' comes out weird when it's rendered, as the k exponent is just floating about. Change to 'first' and 'second' term or something else?
- L. 72: typo default
- L. 150: spectral and \ in front of mu (doesn't render correctly)
- L. 202: available
- L. 207: distribution, incoming
- L.220: received, diurnal
- L. 256: same as line 67
- L. 291: maybe 'Sets whether insolation is diurnally-and-seasonally averaged (``TRUE``), or time dependent (``FALSE``). Default ``FALSE``.'
- L. 296: determining
- L. 301: 'would achieved' to 'would set to'?
- L. 323: They
- L. 329: calculate
- L. 402: calculations

**Comment by ntlewis** [comment]
Hi @matthewjhenry and @RuthG, I've corrected each of the typos you spotted. 

Ruth: I haven't yet done anything regarding the hard coding of the BOG CO2 coeff, or the possibility to include Ozone in the Geen scheme. As neither of these changes have been made to the code yet, I've left any changes relating to them out of the docs. I have, however, included a note saying that the Geen scheme is only stable for fixed SSTs.

I think this is ready to go now, once the Travis check passes and you guys approve it. Would be good to get it in soon :) 

Neil

**Comment by RuthG** [comment]
Just doing a last check. From the red patches on the files changed tab, I think this will remove some references that have been merged in since your pull request. https://github.com/ExeClim/Isca/pull/176/files

Please could you checkout the updated references rst and add your refs to that?  Then I think we're good to go :)

**Comment by RuthG** [comment]
Also change the expect by to 30/11/2020 please! There's not much work needed but I've got a lot of commitments the next couple of months and would rather not set myself up to fail immediately here!

**Comment by ntlewis** [comment]
@RuthG occurrences of date changed. Feel free to merge once the Travis build has passed again.

**Review by matthewjhenry — APPROVED** [review]

**Pull request merged**
